redis:
  image: redis
  expose:
    - 6379
  volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

rabbitmq:
  image: rabbitmq:3.5-management
  expose:
    - 4369
    - 5671
    - 5672
    - 15672
    - 25672
  environment:
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest
    RABBITMQ_DEFAULT_VHOST: /
    RABBITMQ_NODE_PORT: 5672

api:
  image: sstarcher/sensu:0.25.7
  privileged: true
  links:
    - redis
    - rabbitmq
  expose:
    - 4567
  ports:
    - "4567:4567"
  command: api   


sensu:
  image: sstarcher/sensu:0.25.7
  privileged: true
  links:
    - redis
    - rabbitmq
    - api
  command: server

testcontainer:
  build: ./test-container
  privileged: true
  links:
    - rabbitmq

uchiwa:
  image: uchiwa/uchiwa:0.17.1
  privileged: true
  ports:
    - "80:3000"
  links:
    - api:sensu-api
  volumes:
    - ./uchiwa:/config
